site_name: Docs
theme:
  name: material
  palette:
    primary: 'Blue Grey'
    accent: 'Pink'
  features:
      - navigation.tabs
      - content.code.annotate
  language: 'zh'

nav:
  - Home: index.md
  - Algo:
    - sort : algorithm/sort.md
    - search : algorithm/search.md
    - lru : algorithm/lru.md
    - string : algorithm/string.md
    - link : algorithm/link.md
    - Leetcode: algorithm/leetcode.md
  - DataStruct:
    - BST/AVL: ds/dataStruct.md
    - Hash: ds/hash.md
    - RBree: ds/rbtree.md
    - Btree: ds/btree.md
  - System :
    - System: system/sys.md
    - Linux: linux.md
    - IPC: IPC.md
    - Mutex: mutex.md
    - RCU: rcu.md
    - ThreadPool: thread_pool.md
    - ProcessDesc: process_desc.md
    - ThreadSched: thread_sched.md
  - DB:
    - Mysql: db/database.md
    - MysqlOper: db/mysqloper.md
    - MysqlLock: db/lock.md
    - MysqlIndex: db/index.md
    - Redis: db/redis.md
  - Net:
    - Tcp/Ip: net/tcp_ip.md
    - Http: net/http.md
    - Safe: net/safe.md
    - Nginx: net/nginx.md
    - Listen: net/listen.md
    - Epoll: net/epoll.md
    - NetProgram: net/net_program.md
    - Netfilter: net/netfilter.md
  - Language:
    - CPP: lang/cpp.md
    - CppVirtualFun: lang/cppVirtualFun.md
    - C: lang/c.md
    - BackQuestion: lang/back-end.md
  - Design:
    - Pattern : design/designPattern.md
    - Creational : design/create.md
    - Structural : design/struct.md
    - Behavioral : design/behavioral.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
