site_name: Ims Docs
theme: readthedocs
nav:
    - DataStruct: dataStruct.md
    - Algorithms: algorithms.md
    - Database: database.md
    - Http: http.md
    - Tcp/Ip: tcp_ip.md
    - IPC: IPC.md
    - linux: linux.md
    - DesignPattern : designPattern.md
    - CPP: cpp.md
    - CppVirtualFun: cppVirtualFun.md
    - BackQuestion: back-end.md

