site_name: Ims Docs
theme:
  name: material
  palette:
    primary: 'Blue Grey'
    accent: 'Pink'
  feature:
    tabs: true
  #font:
    #text: 'Ubuntu'
    #code: 'Ubuntu Mono'
  language: 'zh'
nav:
    - Home: index.md
    - System: sys.md
    - Linux: linux.md
    - IPC: IPC.md
    - Mutex: mutex.md
    - RCU: rcu.md
    - DataStruct: dataStruct.md
    - Algorithms: algorithms.md
    - Mysql: database.md
    - Redis: redis.md
    - Http: http.md
    - Tcp/Ip: tcp_ip.md
    - Epoll: epoll.md
    - Listen: listen.md
    - NetProgram: net_program.md
    - DesignPattern : designPattern.md
    - CppVirtualFun: cppVirtualFun.md
    - CPP: cpp.md
    - C: c.md
    - ThreadPool: thread_pool.md
    - ProcessDesc: process_desc.md
    - ThreadSched: thread_sched.md
    - Netfilter: netfilter.md
    - BackQuestion: back-end.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde


