site_name: Ims Docs
theme: readthedocs
nav:
    - Home: index.md
    - DataStruct: dataStruct.md
    - Algorithms: algorithms.md
    - Database: database.md
    - Http: http.md
    - Tcp/Ip: tcp_ip.md
    - IPC: IPC.md
    - linux: linux.md
    - DesignPattern : designPattern.md
    - CppVirtualFun: cppVirtualFun.md
    - CPP: cpp.md
    - C: c.md
    - RCU: rcu.md
    - ThreadPool: thread_pool.md
    - ProcessDesc: process_desc.md
    - ThreadSched: thread_sched.md
    - Listen: listen.md
    - BackQuestion: back-end.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
