site_name: Ims Docs
theme: readthedocs
nav:
    - Home: index.md
    - DataStruct: dataStruct.md
    - Sort: sort.md
    - Algorithms: algorithms.md
    - Database: database.md
    - Http: http.md
    - Tcp/Ip: tcp_ip.md
    - IPC: IPC.md
    - Net/cmd: linux_net_cmd.md
    - DesignPattern : designPattern.md
    - CMemoryCategory: cMemoryCategory.md
    - CppVirtualFun: cppVirtualFun.md
    - Question: question.md
    - BackQuestion: back-end.md
    - About: about.md

